import { Header } from "@/components/Header";
import "./globals.css";
import { IBM_Plex_Mono } from "next/font/google";
import { Footer } from "@/components/Footer";

const iBM_Plex_Mono = IBM_Plex_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={iBM_Plex_Mono.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
